# Generated by Django 2.1.7 on 2019-05-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
                ('hidden_sentence', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
            ],
        ),
    ]
