# Generated by Django 2.1.7 on 2019-05-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rhyme',
            field=models.CharField(default='nothing', max_length=100),
        ),
    ]
