# Generated by Django 2.1.7 on 2019-05-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_post_rhyme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
